url: "https://aneacsu.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Andrei Neacsu" # the name of your site, e.g. ACME Corp.

collections:
  posts:
    permalink: /blog/:year/:month/:day/:title
  photo:
    output: true
    permalink: /:collection/